### ISSUE TITLE
Create a better visual README for all the developer process

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#10]
**Should contain the process of opening/solving an issue**

1. Issue information + BEPRO bounty should be available and easy to understand :
- [ ] Name
- [ ] Description
- [ ] All features requested
- [ ] $BEPRO bounty
- [ ] Solution Expected
- [ ] Requesting Github Entity

2. Issue Discussion
3. Development of Issue by the desired developers
4. PR should be submitted with :
- [ ] The `ethereum address` for the BEPRO bounty payment
- [ ] Proposed solution and steps taken
- [ ] Easy to access information
- [ ] Clean PR with prettier 
- [ ] Opt : Twitter handle

**Comment by nelsonvega** [comment]
I'm working on this ticket.

**Comment by Ruiub3i** [comment]
@nelsonvega are you still working on this one?

**Comment by nelsonvega** [comment]
yes, I'm working on this ticket. I will send the PR soon.

**Comment by nelsonvega** [comment]
Is this ticket still outstanding @Ruiub3i ?
