### ISSUE TITLE
Smart Contract - ERC20 Token Lock

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#13]
**Description** 
User should be able to lock their ERC20 Tokens with a Start Date (block.timestamp) and End Date, after the EndDate the user should be able to withdraw their tokens

**Master Variables** 
1. ERC20 address
2. admin (`onlyOwner` modifier)
4. maxAmountToLock
5. minAmountToLock
6. totalAmountStaked (at that moment)

**Features**  
- [ ] `deploy(ERC20Adress)`
- [ ] `lock(amount, endDate)`
- [ ] `setMaxAmountToLock(tokenAmount)`
- [ ] `setMinAmountToLock(tokenAmount)`

**Comment by sgoia** [comment]
I am working on this.

**Comment by sgoia** [comment]
A few ideas need to be clarified here:
1. "ERC20 address" is the BEPRO token address that could be changed in the future by contract admin I guess ?
2. "endDate" is a date in the future that contract admin can set once or modify whenever needed or wanted ?
3. "maxAmountToLock" and "minAmountToLock" must be specific to each user, how many tokens to lock, minimum and maximum amounts I guess

4. "deploy(ERC20Adress)" this must be done by admin only to change token address as we mention in point 1 ?

**Comment by sgoia** [comment]
> A few ideas need to be clarified here:
> 
> 2. "endDate" is a date in the future that contract admin can set once or modify whenever needed or wanted ?
Sorry, this is obvious, the description says it, user should be able to lock their own tokens by specific End Date.

**Comment by Ruiub3i** [comment]
1."ERC20 address" should be a variable to enter in the deploy function
2."endDate" should be set by the user on the "lock(endDate)" function - updated in the description
3."minAmountToLock" & "max.." should be set by the admin and verified in the "lock" function
4. yes! but not to be able to change after the deploy (should be set forever)

**Comment by sgoia** [comment]
ok great, thanks.

**Comment by sgoia** [comment]
Another question that comes up is, once a user lockes up some tokens, he will not be able to lock any new amount until the first lock is released? Or do we handle multiple locking requests for the same user?

**Comment by sgoia** [comment]
We do one lock at a time for now.

**Comment by sgoia** [comment]
I would appreciate someone to grant me permission to push my changes for this issue, thank you.

**Comment by Ruiub3i** [comment]
**Solved - to be paid once the BETA is released**
