### ISSUE TITLE
Need to update npm

### ISSUE THREAD

**Issue by CaCaBlocker** [bepronetwork/bepro-js#142]
I tried to implement the **ERC20Distribution** function for my project, but when I installed the latest version, it didn't work. So I reviewed the module code, and I found that **'ERC20Distribution.sol'** file didn't exist, but I checked that it existed on Git Repository and documentation.

Hope to solve this problem quickly.

Thanks.

**Comment by InterCroneworld** [comment]
Why quickly. Do you have a new customer to cheat. Be carefull with this guy he have stolen our funds.
