### ISSUE TITLE
Smart Contract - Network [@BEPRO]

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#18]
Description A decentralized Development Marketplace for bepro-js

Master Variables

incrementIssueID uint256
closedIdsCount uint256
totalStaked uint256
feeAddress address
feeAddress uint256
Libraries to Inherit

Ownable
ERC20 (beproToken)
Features

openIssue(amount)
updateIssue(issueId, amount)
closeIssue(issue_id, prAddresses, prAmounts, metadata)
getIssueById(issue_id)
getIssuesByAddress(address)

**Comment by Ruiub3i** [comment]
**Requester**  
BEPRO (https://bepro.network)

**Description** 
A decentralized NFT Factory where users are able to open packs with football events

**Master Variables** 
1. incrementIssueID `uint256`
2. closedIdsCount `uint256`
3. totalStaked `uint256`
4. feeAddress `address`
5. feeAddress `uint256`


**Libraries to Inherit** 

- [ ] Ownable
- [ ] ERC20 (beproToken)

**Features**  
- [ ] `createPacks(paks_number, nfts_per_pack, price, series, drop, pack_type, initial_id)` [ADMIN]
- [ ] `openIssue(amount)` 
- [ ] `updateIssue(issueId, amount)`
- [ ] `closeIssue(issue_id, prAddresses, prAmounts, metadata)`
- [ ] `getIssueById(issue_id)`
- [ ] `getIssuesByAddress(address)`

**Comment by andrefcgoncalves** [comment]
When not using the `test=true`, we need to call the `__assert` method but it throws an error: 
`TypeError: Cannot read property 'use' of undefined @ bepro-js/build/models/BEPRO/Network.js (590:73)`

Here's the snippet :
```javascript
const beproNetwork = new Network({
  contractAddress: '0x852D6375c55498B326Fb87C69E16F010d2906C0E',
  opt: {
    web3Connection: web3Connection,
  }
});

await beproNetwork.login();
await beproNetwork.__assert();
```

**Comment by andrefcgoncalves** [comment]
After creating an issue, calling the method `getIssueById` and passing the issue id returned on the creation return s the following:
`{"_id":"0","tokensStaked":"0","creationDate":"1970-01-01T00:00:00.000Z","issueGenerator":"0","votesForApprove":"0","mergeProposalsAmount":0,"finalized":"0","canceled":false}`

**Comment by Ruiub3i** [comment]
First Audit Report (Red4Sec)

Know Issues being solved : 

- [ ] Flash Loan Compromise for Council 25M

[BEPRO Security Audit Report v2.pdf](https://github.com/bepronetwork/bepro-js/files/6662765/BEPRO.Security.Audit.Report.v2.pdf)

**Comment by Mochaaz** [comment]
good
