### ISSUE TITLE
Integrate Circle CI for npm test automated CI

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#24]
- Config.yml is already created on a branch  `circleci-project-setup`

- [ ] All the process should work
- [ ] Should run npm test and verify if it fails or not (report on the github env directly)

**Comment by snack-0verflow** [comment]
@Ruiub3i Just got local environment running tests through `npm run test`. Picking up this ticket. 


Questions:

1. Should all unit tests pass atm?
2. What do you mean by "report on the github env directly"? (like CI pass or failed icon on per commit history in a PR?)

**Comment by snack-0verflow** [comment]
@Ruiub3i 

There are tests failing, is this expected?
<img width="1214" alt="Screenshot 2021-05-03 at 00 39 15" src="https://user-images.githubusercontent.com/36766508/116831626-732b3900-aba8-11eb-86df-2c3dac1d57f0.png">

<img width="1349" alt="Screenshot 2021-05-03 at 00 39 26" src="https://user-images.githubusercontent.com/36766508/116831622-6eff1b80-aba8-11eb-9e8c-2b5a653ec2e8.png">

**Comment by snack-0verflow** [comment]
Status update:
After a brief discussion (with `Samjr_g` and @Ruiub3i) on the BePro's developer community telegram channel, this CI ticket is blocked until tests have been automated using `ganache` to test smart contracts using local private chain and rpc client rather that Eth's public test net.

**Comment by snack-0verflow** [comment]
Merged 🙌🏼

**Comment by Ruiub3i** [comment]
**Solved - to be paid once the BETA is released**
