### ISSUE TITLE
Integrate Automatic Javascript Documentation Build 

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#3]
The goal is to generate automatically a javascript documentation so that new developers can seamlessly add new js code comments like the ones below : 

<img width="387" alt="Screenshot 2021-04-14 at 13 59 23" src="https://user-images.githubusercontent.com/26004658/114714033-9f7e3300-9d29-11eb-8a4a-1e832a94ff02.png">

The solution has to present : 
- [ ] Detect all @param, @description, @return, @function and all js-doc variables
- [ ] Automated NPM script to run (ex : "npm run build")
- [ ] Create a Static Website with all documentation organized 
- [ ] Being able to customize the page look

Ps : Can be used external software (even paid ones)

**Comment by moshmage** [comment]
I was using `typedoc --theme minimal --out ./doc --mode file --disableSources` on a old project I had. I guess I can take a stab at this over the weekend and check if it will work the same way. 

If it does it's just a matter of providing a better template and/or add new functionality to it.

**Comment by Ruiub3i** [comment]
That would be able to work @moshmage. The goal is to fill the above tickers, if you are able that would be great.

Thanks!

**Comment by moshmage** [comment]
> 
> 
> That would be able to work @moshmage. The goal is to fill the above tickers, if you are able that would be great.
> 
> Thanks!

Yep, got jsdoc to work; But it turns out there isn't a "simple" way to create the template. Will get on it :)

One question: Should the template for the documentation live inside the betpro-js project or should it be a dependency ? (I'm leaning for a dependency 'cos I can't think of a _good_ reason for them to live side-by-side the project. But I'll go with what's decided ^^)

**Comment by Ruiub3i** [comment]
Can be a dependency, no problem! :)

**Comment by Ruiub3i** [comment]
**Solved - to be paid once the BETA is released**

**Comment by Gulnawaz357** [comment]
Yar work nai ho rai he plz help
