### ISSUE TITLE
Generate a good documentation for all the JS Models (ERC721Collectibles etc..)

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#4]
Create good js-doc like the one below : 

<img width="444" alt="Screenshot 2021-04-14 at 14 02 52" src="https://user-images.githubusercontent.com/26004658/114714525-1b787b00-9d2a-11eb-8579-efe7e0e40066.png">

**Comment by moshmage** [comment]
I'll take this one @Ruiub3i and I'll learn the methods while doing it :)

as a side note, I was also thinking of changing the docs-template to have the members of the class on the navigation for better access; But I can leave that to a more controlled date :)

**Comment by nelsonvega** [comment]
I can work on this @Ruiub3i . I just want to make sure no one is working on it

**Comment by moshmage** [comment]
> I can work on this @Ruiub3i . I just want to make sure no one is working on it

Sorry @nelsonvega there was already a PR open for this; You're welcome to make improvements, tho!
