### ISSUE TITLE
Create 2 more tabs on the Documentation Page

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#51]
**Description**

Add 2 pages below Documentation [Readme.md]

- Contributing [Contributing.md]
- Rules [Rules.md]

<img width="519" alt="Screenshot 2021-05-25 at 12 37 43" src="https://user-images.githubusercontent.com/26004658/119491597-042fa300-bd56-11eb-98b4-8ca90a3e6356.png">

Add information on Contributing with the info below : 

1. How to create a new feature/contract/product [Non Developer]
2. How to create a new feature/contract/product [Developer]
3. How to be part of an issue [Developer]
4. How to review an issue [Developer]
5. How to use the code available [Developer]
6. How to use $BEPRO [Validator]

**Comment by Ruiub3i** [comment]
2.

- [ ] Fork the Project
- [ ] Create a smart contract inside the `src/contracts/custom/CONTRACT_NAME.sol`
- [ ] Add it to the` index.js` at `interfaces`
- [ ] Build the Javascript Wrapper at `src/models/custom/CONTRACT_NAME.js`
- [ ] Build the unit tests under `tests/custom/CONTRACT_NAME-test.js`
- [ ] Add to the index.js tests

**Comment by moshmage** [comment]
this should be done using [JSDOC Tutorials](https://jsdoc.app/about-tutorials.html) which is then linked in the jsdoc configuration file as 
```
...
    "opts": {
        ...
        "tutorials": "./docs-src/tutorials"
     }
...
```

[more information on how to do this on better docs here](https://github.com/SoftwareBrothers/better-docs#customization)

**Comment by IMPranshu** [comment]
Hey, I want to work on this issue. I got forwarded to this issue from bepro site. Will this issue will also be considered in the bounty program???

**Comment by moshmage** [comment]
Sorry @IMPranshu this issue has been stale for a while and we forgot to clean it. Documentation for bepro-js / dappkit will exist on its own page and is made from the code itself; Along with a gitbook with more examples, it should suffice.
