### ISSUE TITLE
Create Vue app for bepro-js documentation

### ISSUE THREAD

**Issue by moshmage** [bepronetwork/bepro-js#59]
**Describe the feature or project**
The current JSDoc solution is a pain to update and redesign, and while it serves its "quick to market" purpose it does not satisfy as an actual tool developers use;

To fix this, we should create a Vue2 (typescript) application that's able to digest the documentation from bepro-js and serve it under a github-pages website.

We can achieve this by connecting the two repositories with a dispach_event signal, checking out bepro-js repository, build the vue application and deploy a github website.

We'll make use of [kaorun343/vue-property-decorator](https://github.com/kaorun343/vue-property-decorator) in junction with `class-component` notation and [jsdoc-json](https://github.com/tschaub/jsdoc-json).

E2E for the application should be made with [cypress](https://github.com/cypress-io/cypress)

#### High level flows

![image](https://user-images.githubusercontent.com/1077079/119048055-99c5de00-b9b6-11eb-82b6-d97731729535.png)

![image](https://user-images.githubusercontent.com/1077079/119050533-e828ac00-b9b9-11eb-9dc1-f0fa087bbaf6.png)

---

This [vue-app repo](https://github.com/moshmage/bepro-docs) will then be forked by [bepronetwork](https://github.com/bepronetwork) so we can use the main github-pages website

**Bounty**
Bragging rights

**Comment by moshmage** [comment]
Work has started; Work will continue.

**Comment by Ruiub3i** [comment]
Bragging rights conceded!

**Comment by Wizard-maker** [comment]
What is this page about? I'm lost looking at the comments.

**Comment by moshmage** [comment]
> 
> 
> What is this page about? I'm lost looking at the comments.

Essentially, while the documentation page is usable - it isn't easy to update its design. To that end, we thought about doing something that can consume the existing documentation but make a website/pwa that's easier to maintain and update when needed

**Comment by moshmage** [comment]
progress can be seen here https://github.com/moshmage/bepro-docs

**Comment by moshmage** [comment]
@Wizard-maker updated the issue with something that might clear things :)

**Comment by teedavies** [comment]
How far isthe completion of it

**Comment by moshmage** [comment]
a bepro-js documentation app was deemed "too much" and a gitbook was created. closing issue.
