### ISSUE TITLE
Integrate Proxy Javascript Infrastructure to every contract + Javascript Interface

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#6]
Add a Proxy setup _available already in openzeppelin library installed_

The goal is to : 

- [ ] Make every contract upgradable after deployed (with newer features by the `onlyOwner` modifier)
- [ ] Keep the architecture available for older versions for the same contract (Example : NFT Factory v1 & v2 via inputs on the javascript `getERC721Collectibles({customID, contractAddress, version})` call)

**Comment by sgoia** [comment]
I am working on this one.

**Comment by Ruiub3i** [comment]
Deprecated update
