### ISSUE TITLE
[DOC][Minor] 404 in the live documentation for ERC721Contract (options detail link)

### ISSUE THREAD

**Issue by riaje** [bepronetwork/bepro-js#71]
**Describe the bug**
[DOC][Minor] 404 in the live documentation for the ERC721Contract page 

**Reproduction**
- Go on https://bepronetwork.github.io/bepro-js/ERC721Contract.html
- Click on : ERC721Standard~Options on top of the page

This 404 page is on this address: https://bepronetwork.github.io/bepro-js/ERC721Standard.html#~Options
(Maybe it's just because it's not created atm)

**Expected behavior**
A page about options of ERC721Contract

**Comment by nodexchange** [comment]
I wanted to give @moshmage a bit of break from staring at the docs (over and over again), so here is a quick PR. https://github.com/bepronetwork/bepro-js/pull/73

PS. 
Mosh, amazing work!! The docs are looking gorgeous :D 

@Ruiub3i, have a look if things make sense.

**Comment by nodexchange** [comment]
should be solved.

**Comment by riaje** [comment]
It's perfect thanks :) good work
