### ISSUE TITLE
Run automatically "npm build" when pushing a PR to github

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#8]
- [ ] Create a good bash protocol for Github PR + automatic npm run build for npm package updates

_Can be used external libraries via package.json_

**Comment by nelsonvega** [comment]
working on this ticket

**Comment by nelsonvega** [comment]
@Ruiub3i  the issue was resolved and submitted the PR. Please let me know if you have any question

**Comment by Ruiub3i** [comment]
**Solved - to be paid once the BETA is released**
