### ISSUE TITLE
Create a Decentralized Salary Escrow Payment System [ala Sablier.Finance]

### ISSUE THREAD

**Issue by Ruiub3i** [bepronetwork/bepro-js#86]
**Describe the feature or project**
Create a system similar to Sablier Finance where companies are able to add payments to addresses and daily escrow can be made by the employees and users

**Available Examples**
Sablier.Finance acquired by mainframe

**Bounty**
500k BEPRO

**Who are we**
Internal BEPRO

**Comment by sgoia** [comment]
I am interested in this one, working on it.

**Comment by bexyyy** [comment]
interesting
